//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_4_lamaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocktaking
    {
        public int Id { get; set; }
        public int Id_menu { get; set; }
        public int Nominal_quantity { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
